spring:
  application:
    name: games
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

server:
  port: 8080