spring:
  application:
    name: games
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database: postgresql
    open-in-view: false
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

server:
  port: 8080